
import { type NextPage } from "next";

import Head from "next/head";

import { ActionIcon, AppShell, Box, Button, Group, Header, Navbar, rem, useMantineColorScheme } from "@mantine/core";
import { IconSun, IconMoonStars } from '@tabler/icons-react';
import { MainLinks } from "~/components/shell/_main-links";
import { User } from "~/components/shell/_user";

const Home: NextPage = () => {
  
  const { colorScheme, toggleColorScheme } = useMantineColorScheme();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <Button>Hello world</Button>
        
  */}
   <AppShell
      padding="md"
      navbar={
        <Navbar p="xs" width={{ base: 300 }}>
      <Navbar.Section grow mt="md">
        <MainLinks />
      </Navbar.Section>
      <Navbar.Section>
        <User />
      </Navbar.Section>
    </Navbar>
      }
      header={<Header height={60} p="xs">{/* Header content */}</Header>}
      styles={(theme) => ({
        main: { backgroundColor: theme.colorScheme === 'dark' ? theme.colors.dark[8] : theme.colors.gray[0] },
      })}
    >
     <Group sx={{ height: '100%' }} px={20} position="apart">
        x
            <ActionIcon variant="default" onClick={() => toggleColorScheme()} size={30}>
              {colorScheme === 'dark' ? <IconSun size="1rem" /> : <IconMoonStars size="1rem" />}
            </ActionIcon>
          </Group>
    </AppShell>
      </main>
    </>
  );
};

export default Home;


